backend/urls.py
from django.contrib import admin
from django.urls import path, include
from novel import views

from django.views import static ##新增
from django.conf import settings ##新增
from django.conf.urls import url ##新增

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('novel.urls', 'novel'), namespace='home')),  # 定义首页路由
    #　以下是新增
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

novel/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'index/$', views.home, name='home'),  # 首页路由

    url(r'^login/$', views.login, name='login'),  # 登录路由
    url(r'^user_regist/$', views.regist, name='regist'),  # 用户注册路由

    # 退出登录
    url(r'^sign_out/$', views.sign_out, name='sign_out'),

    # 个人中心路由
    url(r'^my_home/$', views.my_space, name='my_home'),  # 个人中心首页
    url(r'^change_password/$', views.change_password, name='change_password'),  # 修改密码
    url(r'^change_information/$',views.change_information,name='change_information'), #修改信息
    url(r'^change/$',views.change,name='change'),  #修改密码请求
    url(r'^tag/$',views.tag,name='tag'),  # 标签页

    # 删除标签
    url(r'^novel/tag/(\w+)/$', views.delete_tag, name='delete_tag'),

    # 登录验证路由
    url(r'^login_inspect/$', views.login_inspect, name='login_inspect'),
    # 注册验证路由
    url(r'^regist_inspect/', views.regist_inspect, name='regist_inspect'),

    
    # 小说搜索路由
    url(r'^novel/search/$', views.search, name='search'),
    
    # 小说按作者搜索路由
    url(r'^novel/author/(\w+)/(\d+)/(\d+)/$', views.search_author, name='search_author'),
    
    # 小说按小说名搜索路由
    url(r'^novel/name/(\w+)/(\d+)/(\d+)/$', views.search_name, name='search_name'),
    # 小说信息路由
    url(r'^novel/(\d+)/$', views.novel_info, name='novel_info'),
    # 小说章节详情路由
    url(r'^novel/(\d+)/(\d+)/$', views.novel_detail, name='novel_detail'),

    # 小说按章阅读量排序路由（json）
    url(r'^novel/read_counts/(\d+)/(\d+)/$', views.list_novels_by_read_counts, name='list_novels_by_read_counts'),

    # 小说按章阅读量排序路由（page）
    url(r'^novel/read_count/(\d+)/(\d+)/$', views.page_by_read_counts, name='page_by_read_counts'),

    # 小说按作者总章阅读量排序路由（page）
    url(r'^novel/author_read_count/(\d+)/(\d+)/$', views.page_by_author_read_counts, name='page_by_author_read_counts'),

    # 小说按收藏检索路由（page）
    url(r'^novel/collect/(\d+)/(\d+)/$', views.page_by_collect, name='page_by_collect'),

    # 小说按标签分类路由（page）
    url(r'^novel/tag/(\w+)/(\d+)/(\d+)/$', views.page_by_tag, name='page_by_tag'),

    # 小说检查是否收藏路由（json）
    url(r'^novel/novel_is_collect/(\d+)/$', views.novel_is_collect, name='novel_is_collect'),

    # 小说切换收藏路由（json）
    url(r'^novel/novel_change_collect/(\d+)/$', views.novel_change_collect, name='novel_change_collect'),

    # 小说封面图路由（json）
    url(r'^novel/get_novel_img/(\w+)/$', views.get_novel_img, name='get_novel_img'),
]

templates/my_backstage/about_me.html
{% extends 'templates/my_backstage/base.html' %}
{% load static %}

{% block about_me %}
<section class="section contact-me" data-section="{% url 'home:my_home' %}">
    <form method="post" action="{% url 'home:change_information' %}">
        <div class="container">
            <div class="section-heading">
                <h2>我的信息</h2>
                <div class="line-dec"></div>
            </div>
            <div class="row">
                <div class="right-content">
                    <div class="container">
                        <form id="contact" action="" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <fieldset>
                                        <input name="username" type="text" class="form-control" id="username"
                                            placeholder="{{ username }}，您的用户名" disabled />
                                    </fieldset>
                                </div>
                                <div class="col-md-12">
                                    <fieldset>
                                        <input name="email" type="text" class="form-control" id="email"
                                            placeholder="{{ information.email }}，您的电子邮件地址" disabled />
                                    </fieldset>
                                </div>
                                <div class="col-md-12">
                                    <fieldset>
                                        <select class="form-control" name="sex">
                                            
                                            <option value="男" {% if information.sex == '男' %} selected {% endif %}>男</option>

                                            <option value="女" {% if information.sex == '女' %} selected {% endif %}>女</option>
                                        </select>
                                    </fieldset>
                                </div>
                                <br /><br />
                                <div class="col-md-12" style="text-align: center">
                                    <fieldset>
                                        <button type="submit" id="form-submit" class="button">
                                            保存
                                        </button>
                                    </fieldset>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>
{% endblock %}

templates/my_backstage/base.html
<!DOCTYPE html>
<html lang="cn">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <link
            href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
            rel="stylesheet"
    />

    <title>用户个人后台</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'my_backstage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'my_backstage/assets/css/fontawesome.css' %}"/>
    <link rel="stylesheet" href="{% static 'my_backstage/assets/css/templatemo-style.css' %}"/>
    <link rel="stylesheet" href="{% static 'my_backstage/assets/css/owl.css' %}"/>
    <link rel="stylesheet" href="{% static 'my_backstage/assets/css/lightbox.css' %}"/>
    <script src="{% static 'my_backstage/vendor/jquery/jquery.min.js' %}"></script>
</head>

<body>
<div id="page-wraper">
    <!-- Sidebar Menu -->
    <div class="responsive-nav">
        <i class="fa fa-bars" id="menu-toggle"></i>
        <div id="menu" class="menu">
            <i class="fa fa-times" id="menu-close"></i>
            <div class="container">
                <div class="image">
                    {% comment %} <a href="{% url 'home:my_home' %}"><img src="{% static 'my_backstage/assets/images/author-image.jpg' %}" alt=""/></a> {% endcomment %}
                </div>
                <div class="author-content">
                    <h4>{{ username }}</h4>
                    <span>个人中心</span>
                </div>
                <nav class="main-nav" role="navigation">
                    <ul>
                        <li><a href="{% url 'home:my_home' %}">个人信息</a></li>
                        <li><a href="{% url 'home:change_password' %}">修改密码</a></li>
                        <li><a href="{% url 'home:tag' %}">喜好标签</a></li>
                        <li><a href="{% url 'home:home' %}">回到首页</a></li>
                        <li><a href="{% url 'home:sign_out' %}">退出登录</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
    {% block about_me %}

    {% endblock %}

    {% block  my_order %}
    {% endblock %}

    {% block change_password %}
    {% endblock %}


</div>

<!-- Scripts -->
<!-- Bootstrap core JavaScript -->
<script src="{% static 'my_backstage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script src="{% static 'my_backstage/assets/js/isotope.min.js' %}"></script>
<script src="{% static 'my_backstage/assets/js/owl-carousel.js' %}"></script>
<script src="{% static 'my_backstage/assets/js/lightbox.js' %}"></script>
<script src="{% static 'my_backstage/assets/js/custom.js' %}"></script>
<script>
    //according to loftblog tut
    $(".main-menu li:first").addClass("active");

    var showSection = function showSection(section, isAnimate) {
        var direction = section.replace(/#/, ""),
            reqSection = $(".section").filter(
                '[data-section="' + direction + '"]'
            ),
            reqSectionPos = reqSection.offset().top - 0;

        if (isAnimate) {
            $("body, html").animate(
                {
                    scrollTop: reqSectionPos
                },
                800
            );
        } else {
            $("body, html").scrollTop(reqSectionPos);
        }
    };

    var checkSection = function checkSection() {
        $(".section").each(function () {
            var $this = $(this),
                topEdge = $this.offset().top - 80,
                bottomEdge = topEdge + $this.height(),
                wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
                var currentId = $this.data("section"),
                    reqLink = $("a").filter("[href*=\\#" + currentId + "]");
                reqLink
                    .closest("li")
                    .addClass("active")
                    .siblings()
                    .removeClass("active");
            }
        });
    };

    $(".main-menu").on("click", "a", function (e) {
        e.preventDefault();
        showSection($(this).attr("href"), true);
    });

    $(window).scroll(function () {
        checkSection();
    });
</script>
</body>
</html>

templates/my_backstage/change_password.html
{% extends 'templates/my_backstage/base.html' %}

{% load static %}

{% block change_password %}
    <section class="section contact-me" data-section="{% url 'home:change_password' %}">
        <div class="container">
          <div class="section-heading">
            <h2>修改密码</h2>
            <div class="line-dec"></div>
          </div>
          <div class="row">
            <div class="right-content">
              <div class="container">
                <form id="contact" action="{% url 'home:change' %}" method="post">
                    {% csrf_token %}
                  <div class="row">
                    <div class="col-md-12">
                      <fieldset>
                        <input
                          name="password"
                          type="password"
                          class="form-control"
                          id="password"
                          placeholder="旧密码"
                          required=""
                        />
                      </fieldset>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <input
                          name="new_password"
                          type="password"
                          class="form-control"
                          id="new_password"
                          placeholder="新密码"
                          required=""
                        />
                      </fieldset>
                    </div>
                                          <div class="col-md-12">
                      <fieldset>
                        <input
                          name="again_password"
                          type="password"
                          class="form-control"
                          id="again_password"
                          placeholder="确认密码"
                          required=""
                        />
                      </fieldset>
                    </div>
                      <div class="col-md-12">
                      <fieldset>
                        <input
                          name="email"
                          type="text"
                          class="form-control"
                          id="email"
                          placeholder="邮箱"
                          required=""
                        />
                      </fieldset>
                    </div>
                    <div class="col-md-12" style="margin-bottom: 5px;">
                      <span style="color: black;">{{ error }}</span>
                    </div>
                    <div class="col-md-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="button">
                          确认
                        </button>
                      </fieldset>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>

{% endblock %}

templates/my_backstage/tag.html
{% extends 'templates/my_backstage/base.html' %}
{% load static %}

{% block about_me %}
<section class="section contact-me" data-section="{% url 'home:my_home' %}">
    <div class="container">
        <div class="section-heading">
            <h2>我的标签</h2>
            <div class="line-dec"></div>
        </div>
        <div class="row">
            <table class="table table-dark">
                <thead class="thead-light">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">关键词</th>
                    <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody>
                {% for tag in tags %}
                    <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ tag.keyword }}</td>
                    <td><button onclick="deleteTag('{{ tag.keyword }}')">删除此喜好标签</button></td>
                    </tr>
                {% endfor %}
                </tbody>
                </table>
        </div>
    </div>
</section>
<script>
    $(function() {
        console.log('ddd')
    })
    function deleteTag(key) {
        $.get(`/novel/tag/${key}/`, function(result){
            console.log(result)
            if (result.code == 1) {
                window.location.reload();
            } else {
            }
        });
    }
</script>
{% endblock %}