backend/urls.py
from django.contrib import admin
from django.urls import path, include
from novel import views

from django.views import static ##新增
from django.conf import settings ##新增
from django.conf.urls import url ##新增

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('novel.urls', 'novel'), namespace='home')),  # 定义首页路由
    #　以下是新增
    url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT}, name='static'),
]

novel/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'index/$', views.home, name='home'),  # 首页路由

    url(r'^login/$', views.login, name='login'),  # 登录路由
    url(r'^user_regist/$', views.regist, name='regist'),  # 用户注册路由

    # 退出登录
    url(r'^sign_out/$', views.sign_out, name='sign_out'),

    # 个人中心路由
    url(r'^my_home/$', views.my_space, name='my_home'),  # 个人中心首页
    url(r'^change_password/$', views.change_password, name='change_password'),  # 修改密码
    url(r'^change_information/$',views.change_information,name='change_information'), #修改信息
    url(r'^change/$',views.change,name='change'),  #修改密码请求
    url(r'^tag/$',views.tag,name='tag'),  # 标签页

    # 删除标签
    url(r'^novel/tag/(\w+)/$', views.delete_tag, name='delete_tag'),

    # 登录验证路由
    url(r'^login_inspect/$', views.login_inspect, name='login_inspect'),
    # 注册验证路由
    url(r'^regist_inspect/', views.regist_inspect, name='regist_inspect'),

    
    # 小说搜索路由
    url(r'^novel/search/$', views.search, name='search'),
    
    # 小说按作者搜索路由
    url(r'^novel/author/(\w+)/(\d+)/(\d+)/$', views.search_author, name='search_author'),
    
    # 小说按小说名搜索路由
    url(r'^novel/name/(\w+)/(\d+)/(\d+)/$', views.search_name, name='search_name'),
    # 小说信息路由
    url(r'^novel/(\d+)/$', views.novel_info, name='novel_info'),
    # 小说章节详情路由
    url(r'^novel/(\d+)/(\d+)/$', views.novel_detail, name='novel_detail'),

    # 小说按章阅读量排序路由（json）
    url(r'^novel/read_counts/(\d+)/(\d+)/$', views.list_novels_by_read_counts, name='list_novels_by_read_counts'),

    # 小说按章阅读量排序路由（page）
    url(r'^novel/read_count/(\d+)/(\d+)/$', views.page_by_read_counts, name='page_by_read_counts'),

    # 小说按作者总章阅读量排序路由（page）
    url(r'^novel/author_read_count/(\d+)/(\d+)/$', views.page_by_author_read_counts, name='page_by_author_read_counts'),

    # 小说按收藏检索路由（page）
    url(r'^novel/collect/(\d+)/(\d+)/$', views.page_by_collect, name='page_by_collect'),

    # 小说按标签分类路由（page）
    url(r'^novel/tag/(\w+)/(\d+)/(\d+)/$', views.page_by_tag, name='page_by_tag'),

    # 小说检查是否收藏路由（json）
    url(r'^novel/novel_is_collect/(\d+)/$', views.novel_is_collect, name='novel_is_collect'),

    # 小说切换收藏路由（json）
    url(r'^novel/novel_change_collect/(\d+)/$', views.novel_change_collect, name='novel_change_collect'),

    # 小说封面图路由（json）
    url(r'^novel/get_novel_img/(\w+)/$', views.get_novel_img, name='get_novel_img'),
]

templates/base-simple.html
<!DOCTYPE html>
<html lang="cn">
{% load static %}

<head>
    <!--
    More Templates Visit ==> Free-Template.co
    -->
    <title>首页</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free Template by Free-Template.co" />
    <meta name="keywords"
        content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="Free-Template.co" />

    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'index/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'index/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'index/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/style.css' %}">
    <script src="{% static 'index/js/jquery.min.js' %}"></script>
</head>

<body data-spy="scroll" data-target="#ftco-navbar" data-offset="200">
    <!-- 头部 -->

    <nav class="navbar navbar-expand-lg navbar-light bg-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home:home' %}">最小说</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> 菜单
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class=""><a href="{% url 'home:home' %}" class="nav-link">首页</a></li>
                    <li class=""><a href="/novel/tag/言情/1/200" class="nav-link">言情</a></li>
                    <li class=""><a href="/novel/tag/纯爱/1/200" class="nav-link">纯爱</a></li>
                    <li class=""><a href="/novel/tag/原创/1/200" class="nav-link">原创</a></li>
                    <li class=""><a href="/novel/tag/衍生/1/200" class="nav-link">衍生</a></li>
                    <li class=""><a href="/novel/read_count/1/20" class="nav-link">热门小说</a></li>
                    <li class=""><a href="/novel/author_read_count/1/20" class="nav-link">热门作者</a></li>
                    {% ifequal username None %}
                    <li class=""><a href="{% url 'home:login' %}" class="nav-link">登录</a></li>
                    <li class=""><a href="{% url 'home:regist' %}" class="nav-link">注册</a></li>
                    {% else %}
                    <li class=""><a href="/novel/collect/1/200" class="nav-link">收藏列表</a></li>
                    <!-- Example single danger button -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            {{ username }}
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url  'home:my_home' %}">个人中心</a>
                            <a class="dropdown-item" href="{% url 'home:change_password' %}">修改密码</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'home:sign_out' %}">登出</a>
                        </div>
                    </div>
                    {% endifequal %}
                </ul>
            </div>
        </div>
    </nav>


    <!-- 下部介绍栏1 -->
    {% block bottom1 %}

    {% endblock %}

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#4586ff" />
        </svg>
    </div>


    <script src="{% static 'index/js/popper.min.js' %}"></script>
    <script src="{% static 'index/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'index/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'index/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'index/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'index/js/jquery.animateNumber.min.js' %}"></script>


    <script src="{% static 'index/js/main.js' %}"></script>


</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="cn">
{% load static %}

<head>
    <!--
    More Templates Visit ==> Free-Template.co
    -->
    <title>首页</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free Template by Free-Template.co" />
    <meta name="keywords"
        content="free bootstrap 4, free bootstrap 4 template, free website templates, free html5, free template, free website template, html5, css3, mobile first, responsive" />
    <meta name="author" content="Free-Template.co" />

    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'index/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'index/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'index/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/style.css' %}">
    <script src="{% static 'index/js/jquery.min.js' %}"></script>
</head>

<body data-spy="scroll" data-target="#ftco-navbar" data-offset="200">
    <!-- 头部 -->

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home:home' %}">最小说</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="oi oi-menu"></span> 菜单
            </button>

            <div class="collapse navbar-collapse" id="ftco-nav">
                <ul class="navbar-nav ml-auto">
                    <li class=""><a href="{% url 'home:home' %}" class="nav-link">首页</a></li>
                    <li class=""><a href="/novel/tag/言情/1/200" class="nav-link">言情</a></li>
                    <li class=""><a href="/novel/tag/纯爱/1/200" class="nav-link">纯爱</a></li>
                    <li class=""><a href="/novel/tag/原创/1/200" class="nav-link">原创</a></li>
                    <li class=""><a href="/novel/tag/衍生/1/200" class="nav-link">衍生</a></li>
                    <li class=""><a href="/novel/read_count/1/20" class="nav-link">热门小说</a></li>
                    <li class=""><a href="/novel/author_read_count/1/20" class="nav-link">热门作者</a></li>
                    {% ifequal username None %}
                    <li class=""><a href="{% url 'home:login' %}" class="nav-link">登录</a></li>
                    <li class=""><a href="{% url 'home:regist' %}" class="nav-link">注册</a></li>
                    {% else %}
                    <li class=""><a href="/novel/collect/1/200" class="nav-link">收藏列表</a></li>
                    <!-- Example single danger button -->
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            {{ username }}
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url  'home:my_home' %}">个人中心</a>
                            <a class="dropdown-item" href="{% url 'home:change_password' %}">修改密码</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'home:sign_out' %}">登出</a>
                        </div>
                    </div>
                    {% endifequal %}
                </ul>
            </div>
        </div>
    </nav>

    <section class="ftco-cover ftco-slant" style="background-image: url({% static 'index/images/bg_3.jpg' %});"
        id="section-home">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center ftco-vh-100">
                <div class="col-md-10">
                    <h1 class="ftco-heading ftco-animate">阅读小说，品味人生</h1>
                    <h2 class="h5 ftco-subheading mb-5 ftco-animate">
                        为您推荐最适合您的小说</h2>
                    <form class="form" method="post" action="{% url 'home:search' %}">
                        {% csrf_token %}
                        
                        <div class="form-group label-floating">
                            <select class="form-control" name="type">
                                <option value="author">按作者搜索</option>
                                <option value="name">按小说名搜索</option>
                            </select>
                        </div>
                        <div class="form-group label-floating">
                            <input type="text" placeholder="关键词" class="form-control" name="key"/>
                        </div>
                        <input type="hidden" class="form-control" name="page" value=1 />
                        <input type="hidden" class="form-control" name="page_size" value=200 />
                        <div class="footer text-center">
                            <span>{{ error }}</span>
                            <input type="submit"  class="btn btn-primary btn-round btn-lg btn-block" value="搜索">
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </section>

    <!-- 下部介绍栏1 -->
    {% block bottom1 %}

    {% endblock %}


    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#4586ff" />
        </svg>
    </div>


    <script src="{% static 'index/js/popper.min.js' %}"></script>
    <script src="{% static 'index/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'index/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'index/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'index/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'index/js/jquery.animateNumber.min.js' %}"></script>


    <script src="{% static 'index/js/main.js' %}"></script>


</body>

</html>

templates/login-page.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/login/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'img/login/favicon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>登录</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
          name='viewport'/>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"/>
    <!-- CSS Files -->
    <link href="{% static 'CSS/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'CSS/now-ui-kit.css' %}" rel="stylesheet"/>
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'CSS/demo.css' %}" rel="stylesheet"/>
    <!-- Canonical SEO -->
    <link rel="canonical" href=""/>
    <!--  Social tags      -->
    <meta name="keywords" content="">
    <meta name="description" content="">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/change' %}"></script>


</head>

<body class="login-page sidebar-collapse">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
        <div class="dropdown button-dropdown">
            <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
                <span class="button-bar"></span>
                <span class="button-bar"></span>
                <span class="button-bar"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-header">选项</a>
                <a class="dropdown-item" href="{% url 'home:home' %}">回到首页</a>
                <a class="dropdown-item" href="#">关于我们</a>
                <a class="dropdown-item" href="#">客服服务</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'home:regist' %}">用户注册</a>
            </div>
        </div>
        <div class="navbar-translate">
            <a class="navbar-brand" href="{% url 'home:login' %}" rel="tooltip" data-placement="bottom">
                登录
            </a>
            <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end"
             data-nav-image="{% static 'img/login/blurred-image-1.jpg' %}">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">回到首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:regist' %}">用户注册</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->
<div class="page-header" filter-color="orange">
    <div class="page-header-image" style="background-image:url({% static 'login.jpg' %})"></div>
    <div class="container">
        <div class="col-md-4 content-center">
            <div class="card card-login card-plain">
                <form class="form" method="post" action="{% url 'home:login_inspect' %}">
                    {% csrf_token %}
                    <div class="header header-primary text-center">
                        <div class="logo-container">
                            <img src="{% static 'img/login/now-logo.png' %}" alt="">
                        </div>
                    </div>
                    <div class="content">
                        <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons users_circle-08"></i>
                                </span>
                            <input type="text" class="form-control" placeholder="用户名" name="username"/>
                        </div>
                        <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons text_caps-small"></i>
                                </span>
                            <input type="password" placeholder="密码" class="form-control" name="password"/>
                        </div>
                    </div>
                    <div class="footer text-center">
                        <span>{{ error }}</span>
                        <input type="submit"  class="btn btn-primary btn-round btn-lg btn-block" value="登录">
                    </div>
                    </form>
                    <div class="pull-left">
                        <h6>
                            <a href="{% url 'home:regist' %}" class="link">创建账号</a>
                        </h6>
                    </div>
                    <div class="pull-right">
                        <h6>
                            <a href="#pablo" class="link">忘记密码?</a>
                        </h6>
                    </div>
            </div>
        </div>
    </div>
</div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static 'js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<!-- Share Library etc -->
<script src="{% static 'js/plugins/jquery.sharrre.js' %}" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/now-ui-kit.js' %}" type="text/javascript"></script>

</html>

templates/regist-page.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/login/apple-icon.png' %}">
    <link rel="icon" type="image/png" href="{% static 'img/login/favicon.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <title>Login Page - Now UI Kit by Creative Tim</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
          name='viewport'/>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"/>
    <!-- CSS Files -->
    <link href="{% static 'CSS/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'CSS/now-ui-kit.css' %}" rel="stylesheet"/>
    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link href="{% static 'CSS/demo.css' %}" rel="stylesheet"/>
    <!-- Canonical SEO -->
    <link rel="canonical" href=""/>
    <!--  Social tags      -->
    <meta name="keywords" content="">
    <meta name="description" content="">
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/change' %}"></script>

</head>

<body class="login-page sidebar-collapse">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-primary fixed-top navbar-transparent " color-on-scroll="400">
    <div class="container">
        <div class="dropdown button-dropdown">
            <a href="#pablo" class="dropdown-toggle" id="navbarDropdown" data-toggle="dropdown">
                <span class="button-bar"></span>
                <span class="button-bar"></span>
                <span class="button-bar"></span>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-header">选项</a>
                <a class="dropdown-item" href="{% url 'home:home' %}">回到首页</a>
                <a class="dropdown-item" href="#">关于我们</a>
                <a class="dropdown-item" href="#">客服服务</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'home:login' %}">登录</a>

            </div>
        </div>
        <div class="navbar-translate">
            <a class="navbar-brand" href="{% url 'home:regist' %}" rel="tooltip" data-placement="bottom">
                注册
            </a>
            <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse justify-content-end"
             data-nav-image="{% static 'img/login/blurred-image-1.jpg' %}">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">回到首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:login' %}">登录</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->
<div class="page-header" filter-color="orange">
    <div class="page-header-image" style="background-image:url({% static 'login.jpg' %})"></div>
    <div class="container">
        <div class="col-md-4 content-center">
            <div class="card card-login card-plain">
                <form class="form" method="post" action="{% url 'home:regist_inspect' %}">
                {% csrf_token %}
                    <div class="header header-primary text-center">
                        <div class="logo-container">
                            <img src="{% static 'img/login/now-logo.png' %}" alt="">
                        </div>
                    </div>
                    <div class="content">
                        <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons users_circle-08"></i>
                                </span>
                            <input type="text" name="username" class="form-control" placeholder="用户名">
                        </div>
                        {% ifequal username 0 %}
                            <span style="color: red">用户名已经被占用</span>
                        {% endifequal %}
                        <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons text_caps-small"></i>
                                </span>
                            <input id="password" type="password" name="password" placeholder="密码" class="form-control"/>
                        </div>
                        <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons text_caps-small"></i>
                                </span>
                            <input id="password_inspect" type="password" name="password_inspect" placeholder="确认密码" class="form-control"/>
                        </div>
                        <div class="input-group form-group-no-border input-lg">
                                <span class="input-group-addon">
                                    <i class="now-ui-icons text_caps-small"></i>
                                </span>
                            <input type="email" name="email" placeholder="邮箱" class="form-control"/>
                        </div>
                    </div>
                    <div class="footer text-center">
                        <span>{{ error }}</span>
                        <input type="submit" class="btn btn-primary btn-round btn-lg btn-block" value="注册">
                    </div>
                    <div class="pull-left">
                        <h6>
                            <a href="{% url 'home:login' %}" class="link">登录</a>
                        </h6>
                    </div>
                    <div class="pull-right">
                        <h6>
                            <a href="#pablo" class="link">帮助?</a>
                        </h6>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/core/jquery.3.2.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="{% static 'js/plugins/bootstrap-switch.js' %}"></script>
<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
<script src="{% static 'js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
<script src="{% static 'js/plugins/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<!-- Share Library etc -->
<script src="{% static 'js/plugins/jquery.sharrre.js' %}" type="text/javascript"></script>
<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/now-ui-kit.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    password=document.getElementById('password').value
    password_inspect=document.getElementById('password_inspect').value
    if (password!=password_inspect){
        document.getElementById('password_inspect').style.color='red'
    }
</script>
</html>